---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v3
  
      - name: Run tests
        run: cargo test --verbose
      - name: Run Clippy
        run: cargo clippy --fix --allow-dirty --allow-staged --release --verbose

      - name: Build
        run: cargo build --release --verbose
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
